In [1]:
import os
import tensorflow as tf
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense, Dropout, Activation
import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_log_error, mean_squared_error
import matplotlib.pyplot as plt
import math


Using TensorFlow backend.


In [2]:
dropcolumns = 0

inputs = pd.read_csv('traincleaned.csv')
testinputs = pd.read_csv('testcleaned.csv')
featureimportance = pd.read_csv('feature importance.csv')
featureimportance = featureimportance.rename(columns={'0': 'importance', '1':'feature'})
featureimportance = featureimportance.drop(columns=['Unnamed: 0'])
featureimportance = featureimportance.sort_values(by='importance')
featureimportance = featureimportance[0:dropcolumns]
featureimportance = featureimportance['feature'].tolist()

inputs = inputs.drop(columns=['SalePrice'])
alldata = pd.concat([inputs, testinputs])
alldata.set_index('Id', inplace=True)
alldata = alldata.fillna(0)
alldata = pd.get_dummies(alldata)
alldata = alldata.drop(columns=['Unnamed: 0'])
print(alldata.shape)
alldata = alldata.drop(columns=featureimportance)
print(alldata.shape)

inputs = alldata.loc[0:1460,]
inputs = inputs.values

testinputs = alldata.loc[1461:]
testinputs = testinputs.values

testinputs

(2919, 311)
(2919, 311)


array([[2.0000e+01, 8.0000e+01, 1.1622e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.0000e+01, 8.1000e+01, 1.4267e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [6.0000e+01, 7.4000e+01, 1.3830e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       ...,
       [2.0000e+01, 1.6000e+02, 2.0000e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [8.5000e+01, 6.2000e+01, 1.0441e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [6.0000e+01, 7.4000e+01, 9.6270e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00]])

In [3]:
import numpy

prices = pd.read_csv('traincleaned.csv')
prices = prices['SalePrice']
prices = np.array(prices)
prices = np.log10(prices)
prices

array([5.31910606, 5.25887663, 5.34927753, ..., 5.42569721, 5.15267048,
       5.16879202])

In [4]:
print(inputs.shape, prices.shape)

(1460, 311) (1460,)


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


X_train, X_test, y_train, y_test = train_test_split(inputs, prices, random_state=1)

scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

X_train = X_train_scale
X_test = X_test_scale

inputs = scaler.fit_transform(inputs)



In [15]:
testinputs

array([[0.        , 0.4       , 0.18414656, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.405     , 0.23212407, ..., 0.        , 1.        ,
        0.        ],
       [0.23529412, 0.37      , 0.22419735, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.        , 0.8       , 0.33611464, ..., 0.        , 0.        ,
        0.        ],
       [0.38235294, 0.31      , 0.16272447, ..., 0.        , 1.        ,
        0.        ],
       [0.23529412, 0.37      , 0.14795937, ..., 0.        , 1.        ,
        0.        ]])

In [9]:
# for C in [.005, .01, .05, .1, 1, 10]:
    
#     for gamma in range(1, 10):
#         gamma = gamma/10
        
#         for epsilon in range(1,10):
#             epsilon = epsilon/10
            
#             clf = SVR(kernel='rbf', C=C, gamma=gamma, epsilon=epsilon)
#             clf.fit(X_train, y_train) 
#             testpredictions = clf.predict(X_test)
#             trainpredictions = clf.predict(X_train)
            
#             testpredictions = np.power(10, testpredictions)
#             trainpredictions = np.power(10, trainpredictions)
#             y_test = np.power(10, y_test)
#             y_train = np.power(10, y_train)

#             testRMSLE = math.sqrt(mean_squared_log_error(y_test, testpredictions))
#             trainRMSLE = math.sqrt(mean_squared_log_error(y_train, trainpredictions))
            
#             testpredictions = np.log10(testpredictions)
#             trainpredictions = np.log10(trainpredictions)
#             y_test = np.log10(y_test)
#             y_train = np.log10(y_train)
                
#             if trainRMSLE < .25:
#                 print(C, gamma, epsilon, round(trainRMSLE, 4), round(testRMSLE,4), round(abs(testRMSLE - trainRMSLE), 4))
            


In [10]:
# lastRMSLE = 999

# for C in range(100,300,10):
    
#     for degree in range(4, 10):
        
#         for epsilon in range(1,10, 1):
#             epsilon = epsilon/10
            
#             for coef0 in range(2,5):
            
#                 clf = SVR(kernel='poly', C=C, gamma='auto', degree=degree, epsilon=epsilon, coef0=coef0)
#                 clf.fit(X_train, y_train) 
                
#                 testpredictions = clf.predict(X_test)
#                 trainpredictions = clf.predict(X_train)

#                 testpredictions = np.power(10, testpredictions)
#                 trainpredictions = np.power(10, trainpredictions)
#                 y_test = np.power(10, y_test)
#                 y_train = np.power(10, y_train)

#                 testRMSLE = math.sqrt(mean_squared_log_error(y_test, testpredictions))
#                 trainRMSLE = math.sqrt(mean_squared_log_error(y_train, trainpredictions))

#                 testpredictions = np.log10(testpredictions)
#                 trainpredictions = np.log10(trainpredictions)
#                 y_test = np.log10(y_test)
#                 y_train = np.log10(y_train)
                
#                 if trainRMSLE < lastRMSLE:
#                     lastRMSLE = trainRMSLE
#                     print(f'C={C}, degree={degree}, epsilon={epsilon}, coef0={coef0}, trainRMSLE = {round(trainRMSLE,4)}, testRMSLE={round(testRMSLE, 4)}, diff={round(abs(testRMSLE - trainRMSLE), 4)}')
                
# print('---Done---')
# #C=130,degree=7,epsilon=0.1,coef0=3 0.1359030945302552 first submission
# #C=190,degree=9,epsilon=0.9,coef0=2 0.1359030945302552 second?
# #C=100,degree=7,epsilon=0.1,coef0=2 0.1359030945302552

In [17]:
clf = SVR(kernel='poly', gamma='auto', C=130,degree=7,epsilon=0.1,coef0=3)
clf.fit(inputs, prices) 
testinputs = scaler.fit_transform(testinputs)
predictions = clf.predict(testinputs)
predictions = np.power(10, predictions)

predictions

array([113756.23199989, 165405.21180164, 161803.63934534, ...,
       143315.37341037, 125312.42958512, 218038.69077144])

In [18]:
# clf = SVR(kernel='rbf', C=50, gamma=0.1, epsilon=0.5)
# clf.fit(X_train, y_train) 
# predictions = clf.predict(testinputs)

In [13]:
submittest = pd.read_csv('testcleaned.csv')
submittest = submittest[['Id']]
submittest['SalePrice'] = predictions
submittest.to_csv('BrandenSubmission.csv', index=False)
submittest.head()

Id      SalePrice
0  1461  113756.232000
1  1462  165405.211802
2  1463  161803.639345
3  1464  170211.010929
4  1465  198502.655850